### ISSUE TITLE
Scroll 할 수 있는 View에서의 Gesture가 Native View에 전달되지 않는 현상

### ISSUE THREAD

**Issue by timevoltex** [note11g/flutter_naver_map#13]
현재 scrollView 안에 naver map을 넣고 사용하려고 계속 시도중인데요..
scrollView안에 들어가면 지도의 모든 touchEvent가 작동하질 않습니다.
혹시 내부에서도 touchEvent를 작동시킬 수 있는 방법이 있을까요??

**Comment by note11g** [comment]
해당 현상은 지금 수정중입니다. 잠시만 기다려주시면 경과 보고 드리겠습니다. 감사합니다.

**Comment by timevoltex** [comment]
감사합니다 :)

**Comment by note11g** [comment]
이슈 다시 찾아오시는 분들을 위한 사용법입니다.
NaverMap 위젯을 initialize 하실 때, `forceGesture` 옵션을 `true`로 주시면, 스크롤 제스처보다 우선적으로 NaverMap에 터치 제스처가 전달됩니다.

**Comment by dylan-kwon** [comment]
0.10.5 버전에서는 `forceGesture` 옵션을 찾을 수 없는데 어떻게 사용할 수 있나요?

**Comment by note11g** [comment]
@dylan-kwon 0.11.0 버전 업데이트를 계획중입니다. 해당 버전 이전까지는 다음과 같이 github commit을 기준으로 사용해주시면 되겠습니다.

```yaml
flutter_naver_map:
    git:
      url: https://github.com/note11g/flutter_naver_map.git
      ref: e6e34f3146a6ad624d43eebdd6b4cda3e1ac6a98
```
