### ISSUE TITLE
iOS 에서 Marker subCaptionHaloColor 가 항상 white 로 되는 현상

### ISSUE THREAD

**Issue by kangmyonggyu** [note11g/flutter_naver_map#27]
Android 에서는 Marker 에 subCaptionHaloColor 에 Color 를 지정하면 지정한 Color가 항상 잘 보이지만
iOS 에서는 Marker subCaptionHaloColor 에 Color 를 지정해도 항상 Colors.white 만 적용되네요!

            _markers.add(
              Marker(
                captionText: tradeType.value == TradeType.Trade
                    ? data["deal_amount_ko"].toString()
                    : data["rent_amount_ko"].toString(),
                captionColor: Colors.white,
                captionHaloColor: Colors.blueAccent,
                captionTextSize: 14.0,
                subCaptionHaloColor: Colors.blueAccent,    <----- iOS 에서 blueAccent Color 가 적용되지 않습니다.
                subCaptionColor: Colors.white,

**Comment by note11g** [comment]
https://github.com/note11g/flutter_naver_map/commit/68930fcefc4cbf83ec565a4ee7780b8ff04ec1cb 해당 커밋에서 수정하였습니다.

다음과 같이 yaml에 종속성을 변경해주시면, 변경사항을 사용하실 수 있습니다.
```yaml
flutter_naver_map:
  git:
    url: https://github.com/note11g/flutter_naver_map.git
    ref: 68930fcefc4cbf83ec565a4ee7780b8ff04ec1cb
```
감사합니다.
