### ISSUE TITLE
iOS환경에서 onPathOverlayTab 작동 안함

### ISSUE THREAD

**Issue by ajsl7942** [note11g/flutter_naver_map#54]
테스트 기기:
 iOS iphone 13pro
AOS S21

버전 0.10.7
Naver Map iOS SDK  v3.16.1

지도상에 PathOverlay 생성시 onPathOverlayTab 부분에 메소드를 적용하였는데,

지도에 그려진 PathOverlay 터치시 iOS 환경에서는 작동하지 않습니다.

안드로이드 에서는 정상작동 확인 하였습니다.

**Comment by note11g** [comment]
@ajsl7942 

3dde946 에서 수정하였습니다.

다음과 같이 yaml에 종속성을 변경해주시면, 변경사항을 사용하실 수 있습니다.
```yaml
flutter_naver_map:
  git:
    url: https://github.com/note11g/flutter_naver_map.git
    ref: 3dde94677eb72553b8f5883b9c21506ff23e7d20
```
감사합니다.

다음 버전이 출시될 때까지, 해당 방법을 이용하여 사용하시면 됩니다.
